<a href="https://colab.research.google.com/github/PratyushPriyamKuanr271776508/pwskills_MachineLearning/blob/main/Assignment_Machine_Learning_Pratyush_Kuanr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **1. What is a parameter?**
A parameter is a variable that the model learns during training to make predictions. Examples include weights and biases in linear regression.

### **2. What is correlation?**
Correlation is a statistical measure that indicates the degree to which two variables move in relation to each other. It ranges from -1 to +1.

### **3. What does negative correlation mean?**
Negative correlation means that as one variable increases, the other decreases. For example, higher temperatures may correlate with lower heating costs.

### **4. Define Machine Learning. What are the main components in Machine Learning?**
**Definition**: Machine Learning is a field of AI that enables systems to learn and improve from experience without being explicitly programmed.

**Main components**:
- **Data**: Input for the model.
- **Model**: The algorithm to learn from data.
- **Loss Function**: Measures prediction error.
- **Optimizer**: Minimizes the loss function.
- **Evaluation**: Assess model performance.


### **5. How does loss value help in determining whether the model is good or not?**
A lower loss value typically indicates better model performance, as it represents the difference between predicted and actual values.

### **6. What are continuous and categorical variables?**
- **Continuous variables**: Numerical values with infinite possibilities (e.g., age, temperature).
- **Categorical variables**: Discrete values or categories (e.g., gender, color).

### **7. How do we handle categorical variables in Machine Learning? What are the common techniques?**
**Techniques**:
1. **Label Encoding**: Assigns numerical labels to categories.
2. **One-Hot Encoding**: Creates binary columns for each category.
3. **Ordinal Encoding**: Assigns ordinal values based on category hierarchy.


### **8. What do you mean by training and testing a dataset?**
Training is used to fit the model, while testing evaluates its performance on unseen data.

### **9. What is sklearn.preprocessing?**
`sklearn.preprocessing` is a module in scikit-learn providing tools for preprocessing data, such as scaling, encoding, and normalizing.


### **10. What is a test set?**
A test set is a subset of data reserved for evaluating the model's performance after training.

### **11. How do we split data for model fitting (training and testing) in Python?**

In [1]:
from sklearn.model_selection import train_test_split

X = [[1], [2], [3], [4], [5]]
y = [1, 2, 3, 4, 5]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### **12. How do you approach a Machine Learning problem?**
Steps:
1. Understand the problem.
2. Collect and preprocess data.
3. Perform Exploratory Data Analysis (EDA).
4. Select a suitable model.
5. Train and validate the model.
6. Evaluate and optimize.
7. Deploy and monitor.


### **13. Why do we have to perform EDA before fitting a model to the data?**
EDA helps understand data distribution, detect outliers, and reveal patterns that influence model selection and preprocessing.

### **14. How can you find correlation between variables in Python**

#### **Using Pandas**
The `corr()` function in Pandas calculates the correlation matrix, which shows the pairwise correlation between variables.

#### **Using Numpy**
You can use `numpy.corrcoef()` for correlation computation.

### **Visualization with Seaborn**
To visualize the correlation matrix:

### **15. What is causation? Explain the difference between correlation and causation with an example.**
**Causation**: One event directly affects another.
**Difference**: Correlation indicates association, while causation shows a cause-effect relationship.

**Example**: Ice cream sales and drowning incidents are correlated (summer), but one does not cause the other.

### **16. What is an Optimizer? What are different types of optimizers?**
An optimizer adjusts model parameters to minimize the loss function.

**Types**:
- Gradient Descent
- Stochastic Gradient Descent (SGD)
- Adam

In [2]:
from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.001)

### **17. What is sklearn.linear_model?**
`sklearn.linear_model` provides tools for linear models such as Linear Regression, Logistic Regression, etc.

### **18. What does model.fit() do?**
Fits the model to training data.

**Arguments**:
- Features (X)
- Target labels (y)

### **19. What does model.predict() do?**
Makes predictions on new data.

**Arguments**:
- Input data (X)

### **20. What is feature scaling? How does it help in Machine Learning?**
**Definition**: Normalizing feature values to a standard scale.

**Helps**: Prevents features with large values from dominating.

### **Scaling Techniques**
1. **Min-Max Scaling**: Scales features to a fixed range, typically [0, 1].
2. **Standardization (Z-Score Scaling)**: Scales data to have a mean of 0 and a standard deviation of 1.
3. **MaxAbs Scaling**: Scales features by their maximum absolute value.
4. **Robust Scaling**: Scales features using the median and interquartile range (IQR), making it robust to outliers.

### **When to Use Which Scaling Method?**
- Use **Min-Max Scaling** for algorithms sensitive to ranges (e.g., neural networks).
- Use **StandardScaler** for algorithms assuming normal distributions (e.g., SVM, PCA).
- Use **RobustScaler** when data has outliers.


In [5]:
#### 1. Using sklearn.preprocessing.StandardScaler (Standardization)
from sklearn.preprocessing import StandardScaler
import numpy as np

# Example data
data = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])

# Standardization
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

print("Standardized Data:\n", data_scaled)

#### 2. Using sklearn.preprocessing.MinMaxScaler (Min-Max Scaling)
from sklearn.preprocessing import MinMaxScaler

# Example data
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

print("Min-Max Scaled Data:\n", data_scaled)

#### 3. Using sklearn.preprocessing.MaxAbsScaler
from sklearn.preprocessing import MaxAbsScaler

scaler = MaxAbsScaler()
data_scaled = scaler.fit_transform(data)

print("MaxAbs Scaled Data:\n", data_scaled)

#### 4. Using sklearn.preprocessing.RobustScaler
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
data_scaled = scaler.fit_transform(data)

print("Robust Scaled Data:\n", data_scaled)

Standardized Data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Min-Max Scaled Data:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
MaxAbs Scaled Data:
 [[0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]
Robust Scaled Data:
 [[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]


### **21. Explain data encoding.**
Data encoding converts categorical variables into numerical forms, such as Label Encoding or One-Hot Encoding.